version: '3.9'

x-common-server-settings: &matrix-settings
  image: ${MATRIX_IMAGE:-matrixdotorg/synapse:v1.51.0}
  entrypoint: bash -c 'python setup.py && python start.py'
  restart: 'no'
  networks:
    - federation
  expose:
    - 8448

x-common-proxy-settings: &proxy-settings
  image: "nginx:1.21.6"
  restart: 'no'
  volumes:
    - ./proxy/certs/:/etc/nginx/conf.d/certs
    - ./proxy/js:/etc/nginx/conf.d/js
    - ./proxy/test.conf:/etc/nginx/conf.d/default.conf
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  entrypoint: sh -c 'rm /etc/nginx/conf.d/js/input.json && touch /etc/nginx/conf.d/js/input.json && chown nginx /etc/nginx/conf.d/js/input.json && /docker-entrypoint.sh nginx -g "daemon off;" -c /etc/nginx/nginx.conf'
  networks:
    - federation

services:
  register_service:
    image: "nginx:1.21.6"
    container_name: registration_service
    volumes:
      - ./registration_service/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8080
    networks:
      federation:
        ipv4_address: 172.0.0.16

  first.server:
    container_name: first.server
    <<: *proxy-settings
    ports:
      - "8080:8080"
    environment:
      - SERVER_NUMBER=first

  first.m_server:
    container_name: first.m_server
    <<: *matrix-settings
    ports:
      - 8008:8008
    volumes:
      - ./config_a/:/data
      - ./root-cert.pem:/app/tvr-root-ca.crt
      - ./import_ca_test.py:/import_ca.py

networks:
  federation:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
